# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI/CD with Github Action

on:
  push:
    branches: [ master ]
    tags:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
    - name: Cache step
      uses: actions/cache@v2
      id: cache-node-modules
      env:
        CACHE_NAME: cache-node-modules
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ env.CACHE_NAME }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ env.CACHE_NAME }}-
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Compile with Gradle
      run: |
        ./gradlew compileJava
        ./gradlew processResources
        ./gradlew classes
  test:
    name: Test
    needs: compile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: permission for gradlew
        run: chmod +x gradlew
      - name: test
        run: |
          ./gradlew compileTestJava
          ./gradlew processTestResources
          ./gradlew testClasses
          ./gradlew test
      - name: report
        uses: actions/upload-artifact@v2
        with:
          name: testreport
          path: build/reports
  assemble:
    name: Assemble
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: permission for gradlew
        run: chmod +x gradlew
      - name: Assemble
        run: |
          ./gradlew jar
          ./gradlew assemble
      - name: store assemble file
        uses: actions/upload-artifact@v2
        with:
          name: buildJar
          path: build/libs/